
package main.java.webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "UsuarioNoExistePostulacion", targetNamespace = "http://webservices.java.main/")
public class UsuarioNoExistePostulacion_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioNoExistePostulacion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioNoExistePostulacion_Exception(String message, UsuarioNoExistePostulacion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public UsuarioNoExistePostulacion_Exception(String message, UsuarioNoExistePostulacion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: main.java.webservices.UsuarioNoExistePostulacion
     */
    public UsuarioNoExistePostulacion getFaultInfo() {
        return faultInfo;
    }

}
