
package logica.webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "OfertaLaboralNoTienePaquete", targetNamespace = "http://webServices.logica/")
public class OfertaLaboralNoTienePaquete_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private OfertaLaboralNoTienePaquete faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public OfertaLaboralNoTienePaquete_Exception(String message, OfertaLaboralNoTienePaquete faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public OfertaLaboralNoTienePaquete_Exception(String message, OfertaLaboralNoTienePaquete faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: logica.webservices.OfertaLaboralNoTienePaquete
     */
    public OfertaLaboralNoTienePaquete getFaultInfo() {
        return faultInfo;
    }

}
