
package logica.webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "TipoPublicacionYaExisteException", targetNamespace = "http://webServices.logica/")
public class TipoPublicacionYaExisteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TipoPublicacionYaExisteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TipoPublicacionYaExisteException_Exception(String message, TipoPublicacionYaExisteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public TipoPublicacionYaExisteException_Exception(String message, TipoPublicacionYaExisteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: logica.webservices.TipoPublicacionYaExisteException
     */
    public TipoPublicacionYaExisteException getFaultInfo() {
        return faultInfo;
    }

}
